# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwift_Study_01' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwift_Study_01

pod 'RxSwift'
pod 'RxCocoa'
  target 'RxSwift_Study_01Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxSwift_Study_01UITests' do
    # Pods for testing
  end

end
