# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Grammar_Study' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Grammar_Study
pod 'RxSwift'
pod 'RxCocoa'
end
